// <auto-generated />
using System;
using CcmsCommercialPlatform.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CcmsCommercialPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129140000_AddProvisioningFields")]
    partial class AddProvisioningFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CcmsCommercialPlatform")
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.AzureWebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AzureTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublisherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("AzureWebhookEvents", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.FeatureSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarketplaceSubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceSubscriptionId", "FeatureId");

                    b.ToTable("FeatureSelections", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.MarketplaceSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AzureActivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureSubscriptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeneficiaryEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeneficiaryObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeneficiaryTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CcmsUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryOther")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CustomerInfoSubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraClientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FeatureSelectionCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IaCDeploymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProvisioningCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvisioningMetadata")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProvisioningRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaserObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaserTenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedToExternalSystemAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhitelistIps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AzureSubscriptionId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("MarketplaceSubscriptions", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plans", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.PlanQuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DimensionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IncludedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OveragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanQuotas", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Subscriptions", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.UsageEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ResourceId");

                    b.ToTable("UsageEvents", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.UsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BillingPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("DimensionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DimensionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportedOverage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "DimensionType", "BillingPeriodStart");

                    b.ToTable("UsageRecords", "CcmsCommercialPlatform");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.FeatureSelection", b =>
                {
                    b.HasOne("CcmsCommercialPlatform.Api.Models.MarketplaceSubscription", "MarketplaceSubscription")
                        .WithMany("FeatureSelections")
                        .HasForeignKey("MarketplaceSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketplaceSubscription");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.PlanQuota", b =>
                {
                    b.HasOne("CcmsCommercialPlatform.Api.Models.Plan", "Plan")
                        .WithMany("Quotas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.Subscription", b =>
                {
                    b.HasOne("CcmsCommercialPlatform.Api.Models.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.UsageRecord", b =>
                {
                    b.HasOne("CcmsCommercialPlatform.Api.Models.Subscription", "Subscription")
                        .WithMany("UsageRecords")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.MarketplaceSubscription", b =>
                {
                    b.Navigation("FeatureSelections");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.Plan", b =>
                {
                    b.Navigation("Quotas");
                });

            modelBuilder.Entity("CcmsCommercialPlatform.Api.Models.Subscription", b =>
                {
                    b.Navigation("UsageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
